; [pytest]
; addopts = -v -s --html=reports/report.html --self-contained-html --reruns 2 --reruns-delay 3
; testpaths = tests
;
; markers =
;     smoke: quick smoke tests
;     regression: long regression tests
;     sanity: core functional tests
;
; ; this texst should be in test folder with following fixtures for rerun
; ; @pytest.mark.flaky(reruns=3, reruns_delay=2)
; ; def test_flaky_example(setup):
; ;     driver = setup
; ;     driver.get("https://opensource-demo.orangehrmlive.com/")
; ;     assert "OrangeHRM" in driver.title
